main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^about/$', views.About.as_view(), name='about'),
    url(r'^overview/$', views.Overview.as_view(), name='overview'),
    url(r'^dummy/$', views.Dummy.as_view(), name='dummy'),
    url(r'^contact/$', views.Contact.as_view(), name='contact'),
    url(r'^help/$', views.Help.as_view(), name='help'),
]

tellylog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tv/', include('tv.urls', namespace='tv')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^watchlog/', include('watchlog.urls', namespace='wlog')),
    url(r'^watchlist/', include('watchlist.urls', namespace='wlist')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tv/urls.py
from django.conf.urls import url

from tv import views

urlpatterns = [
    # e.g. series/12
    url(r'^series/(?P<series_id>[0-9]+)/$', views.SeriesView.as_view(),
        name='series'),
    # e.g. series/12/season/1
    url(r'^series/(?P<series_id>[0-9]+)/season/(?P<season_number>[0-9]+)/$',
        views.SeasonView.as_view(), name='season'),
    url(r'^genres/$', views.GenresView.as_view(), name='genres'),
    url(r'^genres/(?P<genre_id>[0-9]+)$', views.GenresSingleView.as_view(),
        name='genres_single')
]

user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'
urlpatterns = [
    url(r'^sign-up/$', views.SignUp.as_view(), name='sign_up'),
    url(r'^sign-in/$', views.SignInView.as_view(), name='sign_in_view'),
    url(r'^signIn/$', views.SignIn, name='sign_in'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^profile/$', views.Profile.as_view(), name='profile'),
    # url(r'^pwforget/$', views.PWForget.as_view(), name='pwforget'),
    url(r'^password/reset/$', auth_views.password_reset,
        {'post_reset_redirect': '/user/password/reset/done/'},
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': '/user/password/done/'},
        name='password_reset_token'),
    url(r'^password/done/$',
        auth_views.password_reset_complete,
        name='password_done'),
]

user/forms.py
from django.contrib.auth.models import User
from captcha.fields import ReCaptchaField
from django import forms
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    captcha = ReCaptchaField()
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

    def clean_email(self):
        """
        Additional function to check if the given email adress is unique.
        """
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(
                email=email).exclude(username=username).count():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

user/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.core.urlresolvers import reverse_lazy

from user.forms import UserCreateForm


class SignUp(FormView):
    template_name = 'user/signUp.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('main:overview')

    def form_valid(self, form):
        form.save()
        return super(SignUp, self).form_valid(form)


def SignIn(request):
    """
    Function that checks given info with the user database and if info exists
    in the database it signs the user in
    """
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return HttpResponseRedirect('/overview/')
        else:
            return HttpResponseRedirect('/user/sign-in/')
    else:
        return render(request, 'user:sign_in', {})


class SignInView(FormView):
    """
    SignInView. redirects incoming requests
    template_name : takes the given template and rendes it to the view.
    """
    template_name = "user/sign-in.html"
    form_class = AuthenticationForm
    success_url = reverse_lazy('main:overview')


@login_required
def Logout(request):
    """
    Function that logs out a signed in user.

    @login_required: regulates the avaliability of the following function
    so only logged in users can use it
    """
    logout(request)
    return HttpResponseRedirect(reverse('main:index'))


class Profile(LoginRequiredMixin, FormView):
    template_name = 'user/profile.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('main:overview')

    def get_form_kwargs(self):
        kwargs = super(Profile, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(Profile, self).form_valid(form)

user/templates/user/profile.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
    {{ block.super }} - Profile
{% endblock title %}
{% block content %}
    <div class="about-text">
        <p>
            Welcome to your profilepage <Strong>{{ user.username }}</strong>!<br>
            Your email adress is : <Strong>{{ user.email }}</strong><br>
            If you wish to change your password please use this form:
        </p>
        <form action="{% url 'user:profile' %}" method="post" class="sign-in" id="sign-in">
            {% csrf_token %}
            <div class="sign-in__input">
                {{ form }}
            </div>
            <div class="sign-in__submit">
                <button type="submit">Change Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

user/templates/user/pwForget.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
    {{ block.super }} - Password Reset
{% endblock title %}
{% block content %}
    <div class="row">
        {% if user.is_authenticated %}
            <strong>You are already signed in!</strong>
            <a href="{% url 'user:logout' %}">Logout</a>
        {% else %}
            <p>
                Please enter your email here:
            </p>
            <form class="sign-up" method="post" action="{% url 'user:pwforget' %}"
                enctype="multipart/form-data">
                {% csrf_token %}
                <div class="sign-up__fields">
                    {{ form }}
                </div>
                <div class="sign-up__submit">
                    <button type="submit">Send</button>
                </div>
            </form>
        {% endif %}
    </div>
{% endblock content %}

user/templates/user/sign-in.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
    {{ block.super }} - Sign In
{% endblock title %}
{% block content %}
    <div class="row">
        <h1 class="text-center">Sign In</h1>
        {% if user.is_authenticated %}
            You are already signed in.
            Back to <a href="{% url 'main:overview' %}">Overview</a>.
        {% else %}
            <div class="row">
                <form action="{% url 'user:sign_in' %}" method="post" class="sign-in" id="sign-in">
                    {% csrf_token %}
                    <label class="sign-in__label" for="username">Username</label>
                    <div class="sign-in__input">
                        <input type="text" name="username" id="username">
                    </div>
                    <label class="sign-in__label" for="password">Password <a href="{% url 'user:password_reset' %}">(forgot Password?)</a></label>
                    <div class="sign-in__input">
                        <input type="password" name="password" id="password">
                    </div>
                    <div class="sign-in__submit">
                        <button type="submit">Sign in</button>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
{% endblock content %}

user/templates/user/signIn.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
    {{ block.super }} - Sign In
{% endblock title %}
{% block content %}
    <div class="row">
        <h1 class="text-center">Sign In</h1>
        {% if user.is_authenticated %}
            You are already signed in.
            Back to <a href="{% main:overview %}">Overview</a>.
        {% else %}
            <div class="row">
                <form action="{% url 'user:sign_in' %}" method="post" class="sign-in" id="sign-in">
                    {% csrf_token %}
                    <label class="sign-in__label" for="username">Username</label>
                    <div class="sign-in__input">
                        <input type="text" name="username" id="username">
                    </div>
                    <label class="sign-in__label" for="password">Password</label>
                    <div class="sign-in__input">
                        <input type="password" name="password" id="password">
                    </div>
                    <div class="sign-in__submit">
                        <button type="submit">Sign in</button>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
{% endblock content %}

user/templates/user/signUp.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
    {{ block.super }} - Sign Up
{% endblock title %}
{% block content %}
    <div class="row">
        <h1 class="text-center">Sign Up</h1>
        {% if user.is_authenticated %}
            <strong>You are already signed in!</strong>
            <a href="{% url 'user:logout' %}">Logout</a>
        {% else %}
            <form class="sign-up" method="post" action="{% url 'user:sign_up' %}"
                enctype="multipart/form-data">
                {% csrf_token %}
                <div class="sign-up__fields">
                    {{ form }}
                </div>
                <div class="sign-up__submit">
                    <button type="submit">Sign up</button>
                </div>
            </form>
        {% endif %}
    </div>
{% endblock content %}