main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^about/$', views.About.as_view(), name='about'),
    url(r'^overview/$', views.Overview.as_view(), name='overview'),
    url(r'^dummy/$', views.Dummy.as_view(), name='dummy'),
    url(r'^contact/$', views.Contact.as_view(), name='contact'),
    url(r'^help/$', views.Help.as_view(), name='help'),
]

tellylog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tv/', include('tv.urls', namespace='tv')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^watchlog/', include('watchlog.urls', namespace='wlog')),
    url(r'^watchlist/', include('watchlist.urls', namespace='wlist')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tv/urls.py
from django.conf.urls import url

from tv import views

urlpatterns = [
    # e.g. series/12
    url(r'^series/(?P<series_id>[0-9]+)/$', views.SeriesView.as_view(),
        name='series'),
    # e.g. series/12/season/1
    url(r'^series/(?P<series_id>[0-9]+)/season/(?P<season_number>[0-9]+)/$',
        views.SeasonView.as_view(), name='season'),
    url(r'^genres/$', views.GenresView.as_view(), name='genres'),
    url(r'^genres/(?P<genre_id>[0-9]+)$', views.GenresSingleView.as_view(),
        name='genres_single')
]

user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'
urlpatterns = [
    url(r'^sign-up/$', views.SignUp.as_view(), name='sign_up'),
    url(r'^sign-in/$', views.SignInView.as_view(), name='sign_in_view'),
    url(r'^signIn/$', views.SignIn, name='sign_in'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^profile/$', views.Profile.as_view(), name='profile'),
    # url(r'^pwforget/$', views.PWForget.as_view(), name='pwforget'),
    url(r'^password/reset/$', auth_views.password_reset,
        {'post_reset_redirect': '/user/password/reset/done/'},
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': '/user/password/done/'},
        name='password_reset_token'),
    url(r'^password/done/$',
        auth_views.password_reset_complete,
        name='password_done'),
]

main/models.py
# main models

main/forms.py
"""
This file holds all forms for the main app.

"""
from django import forms


class SignInForm(forms.Form):
    """
    SignInForm form. Takes the users username and password and is accessed by
    the user app to confirm if a user and password combination exists in the
    user database.

    Attributes:
        username (forms.CharField): Takes the users username.
        password (forms.CharField): Takes the users password(hidden on page).
    """
    username = forms.CharField(max_length=128)
    password = forms.CharField(
        max_length=128, widget=forms.HiddenInput(), initial=0)

main/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from watchlog.models import Watchlog
from watchlist.models import Watchlist


class Index(TemplateView):
    """
    Index View.
    template_name : takes the given template and rendes it to the view.
    """
    template_name = "main/main.html"

    def get_context_data(self, **kwargs):
        """
        Fill up the context array.

        Args:
            **kwargs: Parameters that where given to the view.

        Returns:
            dict: Context dictionary with all values.
        """
        context = super(Index, self).get_context_data(**kwargs)
        context['wlog_list'] = list(Watchlog.objects.order_by(
            '-episode__series', '-added').distinct('episode__series'))[:12]
        context['wlog_list'].sort(key=lambda x: x.added, reverse=True)
        return context


class About(TemplateView):
    """
    About View.
    template_name : takes the given template and rendes it to the view.
    """
    template_name = "main/about.html"


class Dummy(TemplateView):
    """
    Index View.
    template_name : takes the given template and rendes it to the view.
    """
    template_name = "main/dummy.html"


class Contact(TemplateView):
    """
    Contact View.
    template_name : takes the given template and rendes it to the view.
    """
    template_name = "main/contact.html"


class Help(TemplateView):
    """
    Contact View.
    template_name : takes the given template and rendes it to the view.
    """
    template_name = "main/help.html"


class Overview(LoginRequiredMixin, TemplateView):
    """
    Overview View.
    template_name : takes the given template and rendes it to the view.
    @login_required : this view can only be accessed when the user is
        logged in(signed in).
    login_url : is the url wich is taken when the user is not logged in.
    """
    template_name = "main/overview.html"

    def get_context_data(self, **kwargs):
        """
        Fill up the context array.

        Args:
            **kwargs: Parameters that where given to the view.

        Returns:
            dict: Context dictionary with all values.
        """
        user = self.request.user
        context = super(Overview, self).get_context_data(**kwargs)
        context['wlist_list'] = list(Watchlist.objects.filter(
            user=user).order_by('-added'))[:6]
        context['wlog_list'] = list(Watchlog.objects.filter(
            user=user).order_by(
            '-episode__series', '-added').distinct('episode__series'))[:6]
        context['wlog_list'].sort(key=lambda x: x.added, reverse=True)
        return context

main/templates/main/about.html
{% extends "layout/base.html" %}
{% block title %}
    {{ block.super }} - About
{% endblock title %}
{% block content %}
    <div class="about-text">
        tellylog.net is a non-commercial educational site, all images and data are
        property of TMDb. No copyright infringement is intended.
    </div>
{% endblock content %}

main/templates/main/contact.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
    {{ block.super }} - Contact
{% endblock title %}
{% block content %}
    <div class="about-text">
        If you wish to contact us, please feel free to do so at: <a href="mailto:contact@tellylog.net">mailto:contact@tellylog.net</a>
        <br>This site was created by:<br><br>
        <p class="about-text__data"><strong>Tobias Watzek</strong><br> Goldregengasse 11<br>1220 Vienna<br> Austria</p>
        <p class="about-text__data"><strong>Thomas Rauhofer</strong><br> Sieveringerstrasse 32a<br>1190 Vienna<br> Austria</p>
    </div>
{% endblock content %}

main/templates/main/dummy.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="row">
        <h1>Sorry, this page is still in progress!<br>Back to <a href="{% url 'main:index' %}"> main</a>.</h1>
    </div>
{% endblock content %}

main/templates/main/help.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
    {{ block.super }} - Help
{% endblock title %}
{% block content %}
    <div class="about-text">
    Were does "tellylog" come from, you ask? Well, its a combiniation of the british
    slang for television "telly" and "log", for logging in the sense of keeping
    track of something.<br><br>

    What does tellylog do for you?<br>
    You can:<br>
    <ul class="about-text__list">
        <li class="about-text__list__point">Check episodes of a series you have seen to add them to your <a href="{% url 'wlog:index' %}">Watchlog</a></li>
        <li class="about-text__list__point">get info on which episodes of a series you have already seen on your <a href="{% url 'wlog:index' %}">Watchlog</a></li>
        <li class="about-text__list__point">add the series you wish to see in the future to your <a href="{% url 'wlist:index' %}">Watchlist</a></li>
    </ul>
</div>
{% endblock content %}

main/templates/main/main.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="row">
        <div class="about">
            <div class="about__panel">
                <i class="about__icon fa fa-eye"></i>
                <h3 class="about__heading">Log</h3>
                Ever forget where you left off?<br>
                You can keep track and rate every episode of a series you watched by adding it to your Watchlog.
            </div>
            <div class="about__panel about__panel--light">
                <i class="about__icon fa fa-bookmark"></i>
                <h3 class="about__heading">List</h3>
                Found a series you would like to remember?<br>
                Simply add it to your Watchlist where it stays at your disposal.
            </div>
            <div class="about__panel">
                <i class="about__icon fa fa-search"></i>
                <h3 class="about__heading">Search</h3>
                Are you searching for a series?<br>
                Our search is getting it's data from TMDb which has entries of countless series and their seasons and episodes.
            </div>
        </div>
    </div>
    {% if not user.is_authenticated %}
        <div class="row">
            <form action="{% url 'user:sign_in' %}" method="post" class="sign-in" id="sign-in">
                {% csrf_token %}
                <h2 class="text-center">Sign in</h2>
                <label class="sign-in__label" for="username">Username</label>
                <div class="sign-in__input">
                    <input type="text" name="username" id="username">
                </div>
                <label class="sign-in__label" for="password">Password  <a href="{% url 'user:password_reset' %}">(forgot Password?)</a></label>
                <div class="sign-in__input">
                    <input type="password" name="password" id="password">
                </div>
                <div class="sign-in__submit">
                    <button type="submit">Sign in</button>
                </div>
            </form>
        </div>
    {% endif %}
    {% if wlog_list %}
        <div class="row semilight">
            <div class="gallery">
                <h2 class="gallery__heading">Trending</h2>
                <div class="gallery__wrapper">

                        {% for wlog_entry in wlog_list %}
                            <div class="gallery__poster">
                                <a href="{{ wlog_entry.episode.series.get_absolute_url }}" title="{{ wlog_entry.episode.series.name }}">
                                    {% if wlog_entry.episode.series.poster_small %}
                                        <img src="{{ wlog_entry.episode.series.poster_small.url }}" srcset="{{ wlog_entry.episode.series.poster_large.url }} 600w" alt="{{ wlog_entry.episode.series.name }} Poster" class="gallery__image">
                                    {% else %}
                                        <img src="{% static "img/placeholder-small.jpg" %}" srcset="{% static "img/placeholder.jpg" %} 600w" alt="{{ series.name }} Poster Placeholder" class="gallery__image">
                                    {% endif %}
                                </a>
                            </div>
                        {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

main/templates/main/overview.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block title %}
    {{ block.super }} - Overview
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="gallery">
            <h2 class="gallery__heading"><a href="{% url 'wlog:index' %}">Watchlog</a></h2>
            {% if wlog_list %}
                <p class="gallery__info">Your latest Watchlog entries:</p>
                <div class="gallery__wrapper">
                    {% for wlog_entry in wlog_list %}
                        <div class="gallery__poster gallery__poster--small">
                            <a href="{{ wlog_entry.episode.series.get_absolute_url }}" title="{{ wlog_entry.episode.series.name }}">
                                {% if wlog_entry.episode.series.poster_small %}
                                    <img src="{{ wlog_entry.episode.series.poster_small.url }}" srcset="{{ wlog_entry.episode.series.poster_large.url }} 600w" alt="{{ wlog_entry.episode.series.name }} Poster" class="gallery__image">
                                    <div class="gallery__overlay">
                                        <h3>
                                        {{ wlog_entry.episode.series.name }}
                                        </h3>
                                    </div>
                                {% else %}
                                    <img src="{% static "img/placeholder-small.jpg" %}" srcset="{% static "img/placeholder.jpg" %} 600w" alt="{{ wlog_entry.episode.series.name }} Poster Placeholder" class="gallery__image">
                                    <div class="gallery__overlay gallery__overlay--fix">
                                        <h3>
                                        {{ wlog_entry.episode.series.name }}
                                        </h3>
                                    </div>
                                {% endif %}
                            </a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <h2>There are no entries in your watchlog.</h2>
            {% endif %}
        </div>
    </div>
    <div class="row semilight">
        <div class="gallery">
            <h2 class="gallery__heading"><a href="{% url 'wlist:index' %}">Watchlist</a></h2>
            {% if wlist_list %}
                <p class="gallery__info">Your latest Watchlist entries:</p>
                <div class="gallery__wrapper">
                    {% for wlist_entry in wlist_list %}
                        <div class="gallery__poster gallery__poster--small">
                            <a href="{{ wlist_entry.series.get_absolute_url }}" title="{{ wlist_entry.series.name }}">
                                {% if wlist_entry.series.poster_small %}
                                    <img src="{{ wlist_entry.series.poster_small.url }}" srcset="{{ wlist_entry.series.poster_large.url }} 600w" alt="{{ wlist_entry.series.name }} Poster" class="gallery__image">
                                    <div class="gallery__overlay">
                                        <h3>
                                        {{ wlist_entry.series.name }}
                                        </h3>
                                    </div>
                                {% else %}
                                    <img src="{% static "img/placeholder-small.jpg" %}" srcset="{% static "img/placeholder.jpg" %} 600w" alt="{{ wlist_entry.series.name }} Poster Placeholder" class="gallery__image">
                                    <div class="gallery__overlay gallery__overlay--fix">
                                        <h3>
                                        {{ wlist_entry.series.name }}
                                        </h3>
                                    </div>
                                {% endif %}
                            </a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <h2>There are no entries in your watchlist.</h2>
            {% endif %}
        </div>
    </div>
{% endblock content %}

main/templates/main/sign_out.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css.css' %}" />

<!DOCTYPE html>
<html>
	<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
        <title>sign up</title>
        Here we will create the sign up page<br>
		<a href="{% url 'main:index' %}">Back to main</a>
</html>