search/urls.py
from django.conf.urls import url
from search import views

urlpatterns = [
    url(r'^status/$', views.SearchStatus.as_view(), name='status'),
    url(r'^result/$', views.SearchResult.as_view(), name='result'),
    url(r'^$', views.SearchView.as_view(), name='search'),
]

tellylog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tv/', include('tv.urls', namespace='tv')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^watchlog/', include('watchlog.urls', namespace='wlog')),
    url(r'^watchlist/', include('watchlist.urls', namespace='wlist')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tv/urls.py
from django.conf.urls import url

from tv import views

urlpatterns = [
    # e.g. series/12
    url(r'^series/(?P<series_id>[0-9]+)/$', views.SeriesView.as_view(),
        name='series'),
    # e.g. series/12/season/1
    url(r'^series/(?P<series_id>[0-9]+)/season/(?P<season_number>[0-9]+)/$',
        views.SeasonView.as_view(), name='season'),
    url(r'^genres/$', views.GenresView.as_view(), name='genres'),
    url(r'^genres/(?P<genre_id>[0-9]+)$', views.GenresSingleView.as_view(),
        name='genres_single')
]

search/forms.py
"""Holds all forms of the search app"""
from django import forms


class SearchForm(forms.Form):
    """Form for the search

    Attributes:
        q (forms.CharFiels): Field for the search query
    """
    q = forms.CharField()

search/views.py
"""This file holds the views of the search app."""
from django.http import JsonResponse
from django.views.generic import View, TemplateView
from django.core.urlresolvers import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from watson import search as watson
from celery.result import AsyncResult
from tellylog.celery import app
import search.tasks as tasks


class SearchView(LoginRequiredMixin, TemplateView):
    """View for the search
    Attributes:
        http_method_names (list): Allowed http methodes, only get is allowed
        query (str): Query
        query_param (str): GET parameter for the query
        task_id (str, bool): ID of the search task or False if no results
        template_name (str): Name of the template to render
    """
    http_method_names = ['get']
    query_param = "q"
    template_name = "search/search.html"
    query = ''

    def get_query_param(self):
        """Get the query parameter
        Returns:
            str: Query parameter
        """
        return self.query_param

    def get_query(self, request):
        """Parses the query from the request.
        Args:
            request (object): HTTPRequest
        """
        return request.GET.get(self.get_query_param(), "").strip()

    def start_search(self):
        """Start tmdb search
        Returns:
            bool: False on failure or if nothing was found
            str: Task ID of the search task
        """
        # start the search task
        search_task = tasks.search_online(query=self.query)
        # search task equals to True
        if search_task:
            # get task id of search task
            task_id = search_task.task_id
        else:
            # set task id to false
            task_id = False
        return task_id

    def get_context_data(self, **kwargs):
        """
        Fill up the context array.
        Args:
            **kwargs: Parameters that where given to the view.
        Returns:
            dict: Context dictionary with all values.
        """
        # get the query
        self.query = self.get_query(self.request)
        # set the task id and start the search
        self.task_id = self.start_search()
        # get the existing values of the context array
        context = super(SearchView, self).get_context_data(**kwargs)
        context['query'] = self.query
        context['task_id'] = (self.task_id if
                              self.task_id is not None else False)
        # url to make ajax call to SearchStatus View
        status_url = reverse('search:status')
        status_url = self.request.build_absolute_uri(status_url)
        context['status_url'] = status_url
        # url to make ajax call to SearchResult View
        result_url = reverse('search:result')
        result_url = self.request.build_absolute_uri(result_url)
        context['result_url'] = result_url
        return context


class SearchStatus(LoginRequiredMixin, View):
    """Returns a JSON response with the status of the task
    Attributes:
        http_method_names (list): Allowed http methodes, only post is allowed
    """
    http_method_names = ['get']

    def get(self, request):
        """Return a JSON response with the status of the task
        Args:
            request (object): HTTPRequest object
        Returns:
            object: JsonResponse with the status of the task
        """
        # get the task id from the request
        task_id = request.GET['task_id']
        # get the task via id
        result = AsyncResult(task_id, app=app)
        response = JsonResponse({'status': result.status})
        return response


class SearchResult(LoginRequiredMixin, View):
    """Returns a Json response of a search query
    Attributes:
        http_method_names (list): Allowed http methodes, only post is allowed
    """
    http_method_names = ['get']

    def get(self, request):
        """Returns a Json response of a search query
        Args:
            request (object): HTTPRequest
        Returns:
            object: JsonResponse
        """
        # get query out of request
        query = request.GET['query']
        # search for the query in the database
        search_res = watson.search(query)
        # no search results
        if search_res.count() < 1:
            response = JsonResponse({'search_res': []})
        # search results
        else:
            # list of the search results
            search_res_list = []
            # go through all search results and add them to the list
            for sres in search_res:
                # set the sres to the real result
                sres = sres.object
                # result dict
                res = {}
                # set the values of the res to the sres
                res['name'] = sres.name
                res['overview'] = sres.overview
                res['year'] = (sres.first_air_date.year if
                               sres.first_air_date else None)
                res['genres'] = sres.get_genre_list()
                # try to get the poster url
                try:
                    res['poster'] = sres.poster_large.url
                # no poster is present
                except ValueError:
                    res['poster'] = False
                # url of the series
                res['url'] = sres.get_absolute_url()
                # add the result dict to the search result list
                search_res_list.append(res)
            response = JsonResponse({'search_res': search_res_list})
        return response

tv/views.py
"""This file holds the views of the tv app."""
from django.db.models import Count, Avg
from django.shortcuts import get_object_or_404, get_list_or_404
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from tv.models import Series, Season, Episode
from watchlog.models import Watchlog
from watchlist.models import Watchlist


class SeriesView(TemplateView):
    """
    Series view. Gets a Series and a list of its Seasons.

    Attributes:
        template_name (str): Which template to use.
    """

    template_name = "tv/series.html"

    def get_wlog_log_url(self):
        return self.request.build_absolute_uri(reverse('wlog:log'))

    def get_wlog_unlog_url(self):
        return self.request.build_absolute_uri(reverse('wlog:unlog'))

    def get_wlog_rate_url(self):
        return self.request.build_absolute_uri(reverse('wlog:rate'))

    def get_wlog_calc_rating_url(self):
        return self.request.build_absolute_uri(reverse('wlog:calc_rating'))

    def get_wlist_list_url(self):
        return self.request.build_absolute_uri(reverse('wlist:list'))

    def get_wlist_unlist_url(self):
        return self.request.build_absolute_uri(reverse('wlist:unlist'))

    def get_context_data(self, **kwargs):
        """
        Fill up the context array.

        Args:
            **kwargs: Parameters that where given to the view.

        Returns:
            dict: Context dictionary with all values.
        """
        context = super(SeriesView, self).get_context_data(**kwargs)
        context['series'] = \
            get_object_or_404(Series, pk=context['series_id'])
        seasons = get_list_or_404(Season,
                                  series_id=context['series_id'],
                                  episode_count__gt=0)
        context['seasons'] = list()
        avg_rating = Watchlog.objects \
            .filter(user_id=self.request.user.id,
                    episode__series_id=context['series'].id, rating__gt=0) \
            .aggregate(avg_rating=Avg('rating'))
        avg_rating = avg_rating['avg_rating']
        context['avg_rating'] = avg_rating
        context['wlog_count'] = 0
        for season in seasons:
            wlog_entry = {}
            wlog_entry['wlog_count'] = Watchlog.objects \
                .filter(user_id=self.request.user.id,
                        episode__season_id=season.id) \
                .aggregate(wlog_count=Count('id'))
            wlog_entry['wlog_count'] = wlog_entry['wlog_count']['wlog_count']
            wlog_entry['avg_rating'] = Watchlog.objects \
                .filter(user_id=self.request.user.id,
                        episode__season_id=season.id, rating__gt=0) \
                .aggregate(avg_rating=Avg('rating'))
            wlog_entry['avg_rating'] = wlog_entry['avg_rating']['avg_rating']

            if(wlog_entry['wlog_count'] is 0):
                wlog_entry = None
            context['seasons'].append((season, wlog_entry))
            if wlog_entry:
                context['wlog_count'] += wlog_entry['wlog_count']

        context['genre_list'] = context['series'].get_genre_list()

        try:
            context['wlist'] = Watchlist.objects.get(user=self.request.user,
                                                     series_id=context[
                                                         'series_id']
                                                     )
        except Watchlist.DoesNotExist:
            context['wlist'] = False

        # URLs for AJAX requests
        context['wlog_log_url'] = self.get_wlog_log_url()
        context['wlog_unlog_url'] = self.get_wlog_unlog_url()
        context['wlog_calc_rating_url'] = self.get_wlog_calc_rating_url()
        context['wlist_list_url'] = self.get_wlist_list_url()
        context['wlist_unlist_url'] = self.get_wlist_unlist_url()
        return context


class SeasonView(TemplateView):
    """
    Season view. Gets a Season and a list of its Episodes.

    Attributes:
        template_name (str): Which template to use.
    """

    template_name = "tv/season.html"

    def get_wlog_log_url(self):
        return self.request.build_absolute_uri(reverse('wlog:log'))

    def get_wlog_unlog_url(self):
        return self.request.build_absolute_uri(reverse('wlog:unlog'))

    def get_wlog_rate_url(self):
        return self.request.build_absolute_uri(reverse('wlog:rate'))

    def get_wlist_list_url(self):
        return self.request.build_absolute_uri(reverse('wlist:list'))

    def get_wlist_unlist_url(self):
        return self.request.build_absolute_uri(reverse('wlist:unlist'))

    def get_context_data(self, **kwargs):
        """
        Fill up the context array.

        Args:
            **kwargs: Parameters that where given to the view.

        Returns:
            dict: Context dictionary with all values.
        """
        context = super(SeasonView, self).get_context_data(**kwargs)
        context['series'] = get_object_or_404(Series, pk=context['series_id'])
        context['season'] = get_object_or_404(Season,
                                              series_id=context['series_id'],
                                              number=context['season_number'])
        episodes = get_list_or_404(Episode,
                                   series_id=context['series_id'],
                                   season_id=context['season'].id)
        context['wlog_count'] = 0
        context['episodes'] = list()
        for episode in episodes:
            try:
                wlog_entry = Watchlog.objects.get(user_id=self.request.user.id,
                                                  episode_id=episode.id)
            except Watchlog.DoesNotExist:
                wlog_entry = None
            context['episodes'].append((episode, wlog_entry))
            if wlog_entry:
                context['wlog_count'] += 1
        # URLs for AJAX requests
        context['wlog_log_url'] = self.get_wlog_log_url()
        context['wlog_unlog_url'] = self.get_wlog_unlog_url()
        context['wlog_rate_url'] = self.get_wlog_rate_url()
        return context

tv/templates/tv/genres.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load tellytags %}
{% block title %}
    {{ block.super }} - Genres
{% endblock title %}
{% block content %}
<div class="stats-text">
    Here is a list of genres already in our database:<br>

    {% for genre in genres %}
        <a href="{{ genre.get_absolute_url }}">{{ genre.name }}</a><br>
        {% for entry_series in series %}
            {% for entry_genres in entry_series.genres.name %}
                {% if entry_genres.name is genre.name %}
                    {% if entry.poster_small %}
                        <img width="20%" height="20%" src="{{ entry.poster_small.url }}" srcset="{{ entry.poster_large.url }} 600w" alt="{{ entry.name }} Poster" class="gallery__image">
                    {% else %}
                        <img src="{% static "img/placeholder-small.jpg" %}" srcset="{% static "img/placeholder.jpg" %} 600w" alt="{{ series.name }} Poster Placeholder" class="gallery__image">
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% endfor %}

</div>


{% endblock content %}

tv/templates/tv/genres_single.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load tellytags %}
{% block title %}
    {{ block.super }} - Genres
{% endblock title %}
{% block content %}
<div class="row">
    <div class="gallery">
        <h2 class="gallery__heading"><a href="{% url 'tv:genres' %}">Genres</a></h2>
                {% if series %}
                    {% if is_paginated %}
                        <div class="row">
                            <div class="pagination">
                                <span class="pagination__step-links">
                                    {% if page_obj.has_previous %}
                                        <a class="pagination__link" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-arrow-left"></i></a>
                                    {% endif %}
                                    <span class="pagination__current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a class="pagination__link" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-arrow-right"></i></a>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                    {% endif %}
                    <div class="gallery__wrapper">
                        {% for entry in series %}
                            <div class="gallery__poster">
                                <a href="{{ entry.get_absolute_url }}" title="{{ entry.name }}">
                                    {% if entry.poster_small %}
                                        <img src="{{ entry.poster_small.url }}" srcset="{{ entry.poster_large.url }} 600w" alt="{{ entry.name }} Poster" class="gallery__image">
                                    {% else %}
                                        <img src="{% static "img/placeholder-small.jpg" %}" srcset="{% static "img/placeholder.jpg" %} 600w" alt="{{ series.name }} Poster Placeholder" class="gallery__image">
                                    {% endif %}
                                </a>
                            </div>
                        {% endfor %}
                {% else %}
                    <h3>No Genres present in our database.</h3>
                {% endif %}
                </div>
            </div>
        </div>
        {% if is_paginated %}
            <div class="row">
                <div class="pagination">
                    <span class="pagination__step-links">
                        {% if page_obj.has_previous %}
                            <a class="pagination__link" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-arrow-left"></i></a>
                        {% endif %}
                        <span class="pagination__current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>
                        {% if page_obj.has_next %}
                            <a class="pagination__link" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-arrow-right"></i></a>
                        {% endif %}
                    </span>
                </div>
            </div>
        {% endif %}


{% endblock content %}

tv/templates/tv/search.html
<form action="{% url 'watson:search' %}">
    <input name="q" value="{{request.GET.q}}">
    <input type="submit" value="Go">
</form>

tv/templates/tv/season.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load tellytags %}
{% block title %}
    {{ block.super }} - {{ series.name }} - {{ season.name }}
{% endblock title %}
{% block content %}
    <div class="single-page">
        <div class="row header">
            <div class="single-page__meta">
                <h1 class="single-page__heading">
                {{ season.name }}
                {% if season.air_date %}
                    ({{ season.air_date.year }})
                {% endif %}
                </h1>
                <h2 class="single-page__subheading">
                <a href="{{ series.get_absolute_url }}">{{ series.name }}</a>
                </h2>
                <div class="single-page__controls">
                    {% if wlog_count and wlog_count == season.episode_count %}
                        <span class=" log-btn log-btn--season log-btn--logged" title="Unlog the whole season" data-id="{{ season.id }}" data-kind="season">
                            <i class="fa fa-eye" ></i>
                        </span>
                    {% else %}
                        <span class=" log-btn log-btn--season log-btn--unlogged" title="Log the whole season" data-id="{{ season.id }}" data-kind="season">
                            <i class="fa fa-eye-slash" ></i>
                        </span>
                    {% endif %}
                </div>
            </div>
            <div class="single-page__poster">
                {% if season.poster_small %}
                    <img src="{{ season.poster_small.url }}" srcset="{{ season.poster_large.url }} 600w" alt="{{ season.name }} Poster" class="single-page__img">
                    {% elif series.poster_small %}
                    <img src="{{ series.poster_small.url }}" srcset="{{ series.poster_large.url }} 600w" alt="{{ series.name }} Poster" class="single-page__img">
                {% else %}
                    <img src="{% static "img/placeholder-small.jpg" %}" srcset="{% static "img/placeholder.jpg" %} 600w" alt="{{ series.name }} Poster Placeholder" class="single-page__img">
                {% endif %}
            </div>
        </div>
        <div class="row">
            <ul class="single-page__list single-page__list--small">
                {% for episode, wlog_entry in episodes %}
                        <li class="single-page__entry single-page__entry--small">
                            <div class="single-page__entry__number single-page__entry__number--small">
                                {{ episode.number }}
                            </div>
                            <div class="single-page__entry__link single-page__entry__link--small">
                                {{ episode.name }}
                                {% if episode.air_date %}
                                    - {{ episode.air_date|date:"d.m.Y"}}
                                {% endif %}
                            </div>
                            {% if not episode.airs_in_future %}
                                <div class="single-page__entry__rating rating" data-id="{{ episode.id }}">
                                    {% if wlog_entry %}
                                        {% for i in 5|get_range %}
                                            <span data-rating="{{ i }}" class="rating__btn fa {% fill_rating i wlog_entry.rating %}"></span>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div  class="single-page__entry__btn single-page__entry__btn--small">
                                    {% if wlog_entry %}
                                        <span class="log-btn log-btn--episode log-btn--logged" title="Unlog this episode" data-kind="episode" data-id="{{ episode.id }}">
                                            <i class="fa fa-eye" ></i>
                                        </span>
                                    {% else %}
                                        <span class="log-btn log-btn--episode log-btn--unlogged" title="Log this episode" data-kind="episode" data-id="{{ episode.id }}">
                                        <i class="fa fa-eye-slash" ></i></span>
                                    {% endif %}
                                </div>
                            {% endif %}
                        </li>

                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}
{% block customjs %}
    <script type="text/javascript">
    window.Telly = window.Telly || {};
    window.Telly.series_id = {{ series.id }}
    window.Telly.wlog_log_url = "{{ wlog_log_url }}"
    window.Telly.wlog_unlog_url = "{{ wlog_unlog_url }}"
    window.Telly.wlog_rate_url = "{{ wlog_rate_url }}"
    </script>
{% endblock customjs %}

tv/templates/tv/series.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% load tellytags %}
{% block title %}
    {{ block.super }} - {{ series.name }}
{% endblock title %}
{% block content %}
    <div class="single-page">
        <div class="row header">
            <div class="single-page__meta">
                <h1 class="single-page__heading">
                {{ series.name }}
                {% if series.first_air_date %}
                    ({{ series.first_air_date.year }})
                {% endif %}
                </h1>
                <h2 class="single-page__subheading">
                {% for genre in genre_list %}
                    {{ genre.name }}{% if forloop.last %}{% else %}, {% endif %}
                {% endfor %}
                </h2>
                {% if avg_rating %}
                    <div class="single-page__rating">
                        {% for i in 5|get_range %}
                            <span class="fa {% fill_avg_rating i avg_rating %}"></span>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="single-page__controls">
                    {% if wlog_count and wlog_count == series.number_of_episodes %}
                        <span class=" log-btn log-btn--series log-btn--logged" title="Unlog the whole series" data-id="{{ series.id }}" data-kind="series">
                            <i class="fa fa-eye" ></i>
                        </span>
                    {% else %}
                        <span class=" log-btn log-btn--series log-btn--unlogged" title="Log the whole series" data-id="{{ series.id }}" data-kind="series">
                            <i class="fa fa-eye-slash" ></i>
                        </span>
                    {% endif %}
                    {% if wlog_count == 0 %}
                        {% if wlist %}
                            <span class="list-btn list-btn--listed" title="Remove from list" data-id="{{ series.id }}">
                                <i class="fa fa-bookmark" ></i>
                            </span>
                        {% else %}
                            <span class="list-btn list-btn--unlisted" title="Add to list" data-id="{{ series.id }}">
                                <i class="fa fa-bookmark-o" ></i>
                            </span>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="single-page__poster">
                {% if series.poster_small %}
                    <img src="{{ series.poster_small.url }}" srcset="{{ series.poster_large.url }} 600w" alt="{{ series.name }} Poster" class="single-page__img">
                {% else %}
                    <img src="{% static "img/placeholder-small.jpg" %}" srcset="{% static "img/placeholder.jpg" %} 600w" alt="{{ series.name }} Poster Placeholder" class="single-page__img">
                {% endif %}
            </div>
            <p class="single-page__overview">
                {{ series.overview }}
            </p>
        </div>
        <div class="row">
            <ul class="single-page__list">
                {% for season, wlog_entry in seasons %}
                    <li class="single-page__entry">
                        <a href="{{ season.get_absolute_url }}" class="single-page__entry__link">Season {{ season.number }}
                            {% if season.air_date %}
                                ({{ season.air_date.year }})
                            {% endif %}
                        </a>
                        {% if not season.airs_in_future %}
                            <div  class="single-page__entry__btn">
                                {% if wlog_entry and wlog_entry.wlog_count == season.episode_count %}
                                    <span class="log-btn log-btn--season log-btn--logged" title="Unlog the whole season" data-kind="season" data-id="{{ season.id }}">
                                        <i class="fa fa-eye" ></i>
                                    </span>
                                {% else %}
                                    <span class="log-btn log-btn--season log-btn--unlogged" title="Log the whole season" data-kind="season" data-id="{{ season.id }}">
                                        <i class="fa fa-eye-slash" ></i>
                                    </span>
                                {% endif %}
                            </div>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}
{% block customjs %}
    <script type="text/javascript">
    window.Telly = {};
    window.Telly.series_id = {{ series_id }}
    window.Telly.wlog_log_url = "{{ wlog_log_url }}"
    window.Telly.wlog_unlog_url = "{{ wlog_unlog_url }}"
    window.Telly.wlist_list_url = "{{ wlist_list_url }}"
    window.Telly.wlist_unlist_url = "{{ wlist_unlist_url }}"
    window.Telly.wlog_calc_rating_url= "{{ wlog_calc_rating_url }}"
    {% if wlist %}
        window.Telly.on_wlist = true
    {% else %}
        window.Telly.on_wlist = false
    {% endif %}
    </script>
{% endblock customjs %}