main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^about/$', views.About.as_view(), name='about'),
    url(r'^overview/$', views.Overview.as_view(), name='overview'),
    url(r'^dummy/$', views.Dummy.as_view(), name='dummy'),
    url(r'^contact/$', views.Contact.as_view(), name='contact'),
    url(r'^help/$', views.Help.as_view(), name='help'),
]

search/urls.py
from django.conf.urls import url
from search import views

urlpatterns = [
    url(r'^status/$', views.SearchStatus.as_view(), name='status'),
    url(r'^result/$', views.SearchResult.as_view(), name='result'),
    url(r'^$', views.SearchView.as_view(), name='search'),
]

tellylog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tv/', include('tv.urls', namespace='tv')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^watchlog/', include('watchlog.urls', namespace='wlog')),
    url(r'^watchlist/', include('watchlist.urls', namespace='wlist')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tv/urls.py
from django.conf.urls import url

from tv import views

urlpatterns = [
    # e.g. series/12
    url(r'^series/(?P<series_id>[0-9]+)/$', views.SeriesView.as_view(),
        name='series'),
    # e.g. series/12/season/1
    url(r'^series/(?P<series_id>[0-9]+)/season/(?P<season_number>[0-9]+)/$',
        views.SeasonView.as_view(), name='season'),
    url(r'^genres/$', views.GenresView.as_view(), name='genres'),
    url(r'^genres/(?P<genre_id>[0-9]+)$', views.GenresSingleView.as_view(),
        name='genres_single')
]

user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'
urlpatterns = [
    url(r'^sign-up/$', views.SignUp.as_view(), name='sign_up'),
    url(r'^sign-in/$', views.SignInView.as_view(), name='sign_in_view'),
    url(r'^signIn/$', views.SignIn, name='sign_in'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^profile/$', views.Profile.as_view(), name='profile'),
    # url(r'^pwforget/$', views.PWForget.as_view(), name='pwforget'),
    url(r'^password/reset/$', auth_views.password_reset,
        {'post_reset_redirect': '/user/password/reset/done/'},
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': '/user/password/done/'},
        name='password_reset_token'),
    url(r'^password/done/$',
        auth_views.password_reset_complete,
        name='password_done'),
]

templates/layout/base.html
{% load staticfiles %}
{% load tellytags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf8">
        <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <title>{% block title %}tellylog{% endblock title %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Raleway|Roboto' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
</head>
<body>
    <div class="wrapper">
        <div class="page">
            <header class="header">
                <div class="row">
                    <div id="logo" class="header__logo">
                        {% if user.is_authenticated %}
                            <a href="{% url 'main:overview' %}">tellylog</a>
                        {% else %}
                            <a href="{% url 'main:index' %}">tellylog</a>
                        {% endif %}
                    </div>
                    {% if user.is_authenticated %}
                        <div id="nav-toggle" class="header__navtoggle">
                            <a class="js-menu-trigger sliding-panel-button">
                                <i class="fa fa-bars fa-lg"></i>
                            </a>
                        </div>
                        <div class="header__searchbar">
                            <form method="get" action="{% url 'search:search' %}" class="searchbar" role="search">
                                <div class="searchbar__field">
                                    <input type="search" name="q" placeholder="Enter Search" />
                                </div>
                                <div class="searchbar__submit">
                                    <button type="submit" class="searchbar__submit">
                                    <i class="fa fa-search fa-lg"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                        <nav class="js-menu sliding-panel-content">
                            {% block navpanel %}
                                <ul>
                                    <li class="sliding-panel__entry {% active 'main:overview' %}"><a href="{% url 'main:overview' %}">Overview</a></li>
                                    <li class="sliding-panel__entry {% active 'wlog:index' %}"><a href="{% url 'wlog:index' %}">Watchlog</a></li>
                                    <li class="sliding-panel__entry {% active 'wlist:index' %}"><a href="{% url 'wlist:index' %}">Watchlist</a></li>
                                    <li class="sliding-panel__entry {% active 'main:dummy' %}"><a href="{% url 'main:dummy' %}">Achievements</a></li>
                                    <li class="sliding-panel__entry {% active 'tv:genres' %}"><a href="{% url 'tv:genres' %}">Genres</a></li>
                                    <li class="sliding-panel__entry {% active 'user:profile' %}"><a href="{% url 'user:profile' %}">Profile</a></li>
                                    <li class="sliding-panel__entry {% active 'wlog:stats' %}"><a href="{% url 'wlog:stats' %}">Stats</a></li>
                                    <li class="sliding-panel__entry {% active 'user:logout' %}"><a href="{% url 'user:logout' %}">Logout</a></li>
                                </ul>
                            {% endblock navpanel %}
                        </nav>
                    {% else %}
                        <div class="header__signup">
                            <a href="{% url 'user:sign_up' %}">
                                <button>
                                Sign Up
                                </button>
                            </a>
                        </div>
                    {% endif %}
                    <div class="js-menu-screen sliding-panel-fade-screen"></div>
                </div>
            </header>
            {% block content %}
            {% endblock content %}
        </div>
        <footer class="footer">
            <ul class="footer__linklist">
                <li class="footer__linkitem"><a class="footer__link" href="{% url 'main:about' %}">About</a></li>
                <li class="footer__linkitem"><a class="footer__link" href="{% url 'main:help' %}">Help</a></li>
                <li class="footer__linkitem"><a class="footer__link" href="{% url 'main:contact' %}">Contact</a></li>
            </ul>
            <div class="footer__info">
                tellylog uses the TMDb API but is not endorsed or certified by TMDb.
            </div>
        </footer>
    </div>
    {% block customjs %}
        {% comment %}
        Used for custom scripts before the main script is included.
        {% endcomment %}
    {% endblock customjs %}
    <script type="text/javascript" src="{% static 'javascript/main.js' %}"></script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-73770288-1', 'auto');
        ga('send', 'pageview');

    </script>
</body>
</html>